import{findProductByCode}from'./productStore';
let active=false,stream=null,raf=0,last='',lastAt=0;
const text={ru:{title:'Сканер штрихкода',hint:'Наведите камеру на штрихкод товара',close:'Закрыть',unsupported:'Этот браузер не поддерживает распознавание штрихкодов камерой.',camera:'Не удалось открыть камеру. Разрешите доступ к камере.',unknown:'Товар с таким штрихкодом не найден',create:'Создать товар',cancel:'Отмена'},hy:{title:'Շտրիխ կոդի սկաներ',hint:'Տեսախցիկը ուղղեք ապրանքի շտրիխ կոդին',close:'Փակել',unsupported:'Այս բրաուզերը չի աջակցում տեսախցիկով շտրիխ կոդի ճանաչմանը։',camera:'Չհաջողվեց բացել տեսախցիկը։ Թույլատրեք տեսախցիկի հասանելիությունը։',unknown:'Այս շտրիխ կոդով ապրանք չի գտնվել',create:'Ստեղծել ապրանք',cancel:'Չեղարկել'},en:{title:'Barcode scanner',hint:'Point the camera at the product barcode',close:'Close',unsupported:'This browser does not support camera barcode detection.',camera:'Could not open the camera. Allow camera access.',unknown:'No product found with this barcode',create:'Create product',cancel:'Cancel'}};
const lang=()=>localStorage.getItem('cia-pos-language')||'ru',t=k=>text[lang()]?.[k]||text.ru[k];
function stop(){active=false;cancelAnimationFrame(raf);stream?.getTracks().forEach(x=>x.stop());stream=null;document.querySelector('.cia-scanner-overlay')?.remove()}
function setReactInput(input,value){const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')?.set;setter?.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))}
function addKnownProduct(code){const product=findProductByCode(code);if(!product)return false;stop();const input=document.querySelector('.catalog-side .search-box input');if(input){setReactInput(input,code);setTimeout(()=>{const card=document.querySelector('.catalog-side .catalog-card');card?.click();setReactInput(input,'')},80)}return true}
function unknown(code){stop();window.dispatchEvent(new CustomEvent('cia-pos-unknown-barcode',{detail:{barcode:code}}));}
export async function openCameraBarcodeScanner(){if(active)return;if(!('BarcodeDetector'in window)){alert(t('unsupported'));return}active=true;const overlay=document.createElement('div');overlay.className='cia-scanner-overlay';overlay.innerHTML=`<div class="cia-scanner-head"><b>${t('title')}</b><button type="button">×</button></div><div class="cia-scanner-view"><video autoplay muted playsinline></video><div class="cia-scanner-frame"></div></div><p>${t('hint')}</p>`;document.body.appendChild(overlay);overlay.querySelector('button').onclick=stop;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});const video=overlay.querySelector('video');video.srcObject=stream;await video.play();const detector=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e','code_128','code_39','itf']});const scan=async()=>{if(!active)return;try{const codes=await detector.detect(video);const value=codes[0]?.rawValue?.trim();if(value&&value===last&&Date.now()-lastAt<1200)return raf=requestAnimationFrame(scan);if(value){last=value;lastAt=Date.now();if(!addKnownProduct(value))unknown(value);return}}catch{}raf=requestAnimationFrame(scan)};scan()}catch(e){stop();alert(t('camera'))}}
function clickHandler(e){const box=e.target.closest?.('.search-box');if(!box)return;const icon=e.target.closest?.('svg');if(icon&&icon===box.querySelector('svg:last-child')){e.preventDefault();e.stopPropagation();openCameraBarcodeScanner()}}
document.addEventListener('click',clickHandler,true);
window.CIAPOSBarcodeScanner={open:openCameraBarcodeScanner,stop};
