import{useEffect,useState}from'react';
export const LANG_KEY='cia-pos-language';
export const LANGS=[{code:'ru',label:'РУС'},{code:'hy',label:'ՀԱՅ'},{code:'en',label:'ENG'}];
const D={
ru:{catalog:'Каталог',products:'Товары',categories:'Категории',allProducts:'Все товары',addProduct:'Добавить товар',addCategory:'Добавить категорию',edit:'Изменить',back:'Назад',search:'Поиск товара, кода или штрихкода',product:'Товар',price:'Цена',barcode:'Штрихкод',unit:'Ед.',action:'Действие',name:'Название',category:'Категория',department:'Отдел HDM',productCode:'Код товара HDM',photo:'Фото товара',addPhoto:'Добавить фото',replace:'Заменить',remove:'Удалить',cancel:'Отмена',save:'Сохранить изменения',visible:'Товар виден на кассе',hidden:'Товар скрыт с кассы',newProduct:'Новый товар',newCategory:'Новая категория',editCategory:'Изменить категорию',items:'товаров',prepared:'Товары и категории · подготовлено для HDM',photoHint:'Автоматически уменьшаем до 512 px и WebP ~74%.',marking:'Требовать Data Matrix / eMark',categoryName:'Название категории',shop:'Магазин',restaurant:'Ресторан',shiftOpen:'Смена открыта',shiftClosed:'Смена закрыта',newSale:'Новая продажа',sale:'Продажа',cashDesk:'Касса №1',checkEmpty:'Чек пуст',orderEmpty:'Заказ пуст',addItems:'Добавьте товары',amount:'Сумма',total:'Итого',pay:'Оплатить',precheck:'Пречек',printing:'Печать...',menu:'Меню',all:'Все',tables:'Столы',selectTable:'Выберите стол',newOrder:'Новый заказ',free:'Свободен',openOrder:'Открыт заказ',reserved:'Бронь',guests:'Гости',comment:'Комментарий',check:'Чек',service:'Обслуживание 10%',serviceFee:'Сервисный сбор',workMode:'Режим работы',changeLater:'Можно изменить позже.',shopHint:'Быстрая продажа без столов и гостей',restaurantHint:'Столы, гости, пречек и обслуживание',positions:'поз.',openSale:'Открытый заказ'},
hy:{catalog:'Կատալոգ',products:'Ապրանքներ',categories:'Կատեգորիաներ',allProducts:'Բոլոր ապրանքները',addProduct:'Ավելացնել ապրանք',addCategory:'Ավելացնել կատեգորիա',edit:'Փոփոխել',back:'Հետ',search:'Որոնել ապրանք, կոդ կամ շտրիխ կոդ',product:'Ապրանք',price:'Գին',barcode:'Շտրիխ կոդ',unit:'Չափ. միավոր',action:'Գործողություն',name:'Անվանում',category:'Կատեգորիա',department:'ՀԴՄ բաժին',productCode:'ՀԴՄ ապրանքի կոդ',photo:'Ապրանքի նկար',addPhoto:'Ավելացնել նկար',replace:'Փոխարինել',remove:'Հեռացնել',cancel:'Չեղարկել',save:'Պահպանել փոփոխությունները',visible:'Ապրանքը տեսանելի է դրամարկղում',hidden:'Ապրանքը թաքցված է դրամարկղից',newProduct:'Նոր ապրանք',newCategory:'Նոր կատեգորիա',editCategory:'Փոփոխել կատեգորիան',items:'ապրանք',prepared:'Ապրանքներ և կատեգորիաներ · պատրաստ է ՀԴՄ-ի համար',photoHint:'Ավտոմատ փոքրացվում է մինչև 512 px և WebP ~74%.',marking:'Պահանջել Data Matrix / eMark',categoryName:'Կատեգորիայի անվանում',shop:'Խանութ',restaurant:'Ռեստորան',shiftOpen:'Հերթափոխը բաց է',shiftClosed:'Հերթափոխը փակ է',newSale:'Նոր վաճառք',sale:'Վաճառք',cashDesk:'Դրամարկղ №1',checkEmpty:'Կտրոնը դատարկ է',orderEmpty:'Պատվերը դատարկ է',addItems:'Ավելացրեք ապրանքներ',amount:'Գումար',total:'Ընդամենը',pay:'Վճարել',precheck:'Նախնական հաշիվ',printing:'Տպվում է...',menu:'Մենյու',all:'Բոլորը',tables:'Սեղաններ',selectTable:'Ընտրեք սեղան',newOrder:'Նոր պատվեր',free:'Ազատ',openOrder:'Բաց պատվեր',reserved:'Ամրագրված',guests:'Հյուրեր',comment:'Մեկնաբանություն',check:'Կտրոն',service:'Սպասարկում 10%',serviceFee:'Սպասարկման վճար',workMode:'Աշխատանքի ռեժիմ',changeLater:'Կարելի է փոխել ավելի ուշ։',shopHint:'Արագ վաճառք առանց սեղանների և հյուրերի',restaurantHint:'Սեղաններ, հյուրեր, նախնական հաշիվ և սպասարկում',positions:'դիրք',openSale:'Բաց պատվեր'},
en:{catalog:'Catalog',products:'Products',categories:'Categories',allProducts:'All products',addProduct:'Add product',addCategory:'Add category',edit:'Edit',back:'Back',search:'Search product, code or barcode',product:'Product',price:'Price',barcode:'Barcode',unit:'Unit',action:'Action',name:'Name',category:'Category',department:'HDM department',productCode:'HDM product code',photo:'Product photo',addPhoto:'Add photo',replace:'Replace',remove:'Remove',cancel:'Cancel',save:'Save changes',visible:'Product visible at POS',hidden:'Product hidden from POS',newProduct:'New product',newCategory:'New category',editCategory:'Edit category',items:'products',prepared:'Products and categories · HDM ready',photoHint:'Automatically resized to 512 px and WebP ~74%.',marking:'Require Data Matrix / eMark',categoryName:'Category name',shop:'Shop',restaurant:'Restaurant',shiftOpen:'Shift open',shiftClosed:'Shift closed',newSale:'New sale',sale:'Sale',cashDesk:'Register #1',checkEmpty:'Receipt is empty',orderEmpty:'Order is empty',addItems:'Add products',amount:'Amount',total:'Total',pay:'Pay',precheck:'Precheck',printing:'Printing...',menu:'Menu',all:'All',tables:'Tables',selectTable:'Select a table',newOrder:'New order',free:'Free',openOrder:'Open order',reserved:'Reserved',guests:'Guests',comment:'Comment',check:'Receipt',service:'Service 10%',serviceFee:'Service charge',workMode:'Work mode',changeLater:'You can change it later.',shopHint:'Quick sales without tables or guests',restaurantHint:'Tables, guests, precheck and service',positions:'items',openSale:'Open order'}};
export const getLanguage=()=>localStorage.getItem(LANG_KEY)||'ru';
export const setLanguage=lang=>{localStorage.setItem(LANG_KEY,lang);document.documentElement.lang=lang;window.dispatchEvent(new CustomEvent('cia-pos-language-changed',{detail:lang}))};
export const tr=(key,lang=getLanguage())=>D[lang]?.[key]||D.ru[key]||key;
export function useLanguage(){const[lang,setLang]=useState(getLanguage);useEffect(()=>{document.documentElement.lang=lang;const f=e=>setLang(e.detail||getLanguage());window.addEventListener('cia-pos-language-changed',f);return()=>window.removeEventListener('cia-pos-language-changed',f)},[lang]);return{lang,setLang:setLanguage,t:key=>tr(key,lang)}}
