import React,{useEffect,useRef,useState}from'react';
import{Camera,X,ScanLine}from'lucide-react';

const WANTED=['data_matrix','ean_13','ean_8','upc_a','upc_e','code_128','code_39','itf','qr_code'];
const validGtin=value=>{if(!/^\d+$/.test(value)||![8,12,13].includes(value.length))return true;const digits=value.split('').map(Number),check=digits.pop();let sum=0;for(let i=digits.length-1,pos=0;i>=0;i--,pos++)sum+=digits[i]*(pos%2===0?3:1);return(10-(sum%10))%10===check};
const cleanValue=value=>String(value??'').replace(/^\uFEFF/,'').trim();

export default function BarcodeScanner({onDetected,onClose,onScanResult,title='Сканировать код',hint='Наведите камеру на EAN, QR или Data Matrix'}){
 const videoRef=useRef(null),streamRef=useRef(null),timerRef=useRef(null),busyRef=useRef(false),detectedRef=useRef(false),candidateRef=useRef({value:'',format:'',hits:0}),onDetectedRef=useRef(onDetected),onScanResultRef=useRef(onScanResult),[error,setError]=useState(''),[ready,setReady]=useState(false),[formats,setFormats]=useState([]),[lastCandidate,setLastCandidate]=useState(null);
 useEffect(()=>{onDetectedRef.current=onDetected;onScanResultRef.current=onScanResult},[onDetected,onScanResult]);
 useEffect(()=>{let alive=true;const stop=()=>{if(timerRef.current){clearInterval(timerRef.current);timerRef.current=null}streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null};
  (async()=>{try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Камера недоступна. Откройте CIA POS через HTTPS или Android-приложение.');if(!('BarcodeDetector'in globalThis))throw new Error('Сканер кодов не поддерживается этим браузером.');const supported=await globalThis.BarcodeDetector.getSupportedFormats();const enabled=WANTED.filter(x=>supported.includes(x));setFormats(enabled);if(!enabled.length)throw new Error('Сканирование кодов не поддерживается на этом устройстве.');const detector=new globalThis.BarcodeDetector({formats:enabled});const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});if(!alive){stream.getTracks().forEach(t=>t.stop());return}streamRef.current=stream;const video=videoRef.current;if(!video){stop();return}video.srcObject=stream;await video.play();if(!alive)return;setReady(true);
   timerRef.current=setInterval(async()=>{if(!alive||detectedRef.current||busyRef.current||!videoRef.current||videoRef.current.readyState<2)return;busyRef.current=true;try{const codes=await detector.detect(videoRef.current),code=codes?.[0];const value=cleanValue(code?.rawValue),format=String(code?.format||'unknown');if(!value||(format!=='data_matrix'&&!validGtin(value))){candidateRef.current={value:'',format:'',hits:0};return}const same=candidateRef.current.value===value&&candidateRef.current.format===format;candidateRef.current=same?{value,format,hits:candidateRef.current.hits+1}:{value,format,hits:1};setLastCandidate({value,format});if(candidateRef.current.hits>=2&&!detectedRef.current){detectedRef.current=true;const result={value,format,isDataMatrix:format==='data_matrix',isQr:format==='qr_code'};stop();onScanResultRef.current?.(result);onDetectedRef.current?.(value,result)}}catch{}finally{busyRef.current=false}},180);
  }catch(e){if(alive){setReady(false);setError(e?.message||'Не удалось открыть камеру')}}})();return()=>{alive=false;stop()};
 },[]);
 const dmSupported=formats.includes('data_matrix');
 return <div className="barcode-scanner-bg"><div className="barcode-scanner"><div className="barcode-scanner-head"><span><ScanLine/> {title}</span><button type="button" onClick={onClose}><X/></button></div><div className="barcode-camera"><video ref={videoRef} playsInline muted autoPlay/><div className="barcode-frame"><i/><i/><i/><i/></div>{!ready&&!error&&<div className="barcode-camera-state"><Camera/>Открываем камеру…</div>}{error&&<div className="barcode-camera-state error">{error}</div>}</div><p>{error?'Закройте окно и проверьте разрешение камеры.':hint}</p>{ready&&<div style={{padding:'0 18px 16px',fontSize:12,color:'#9fb0c2',textAlign:'center'}}>{dmSupported?'Data Matrix ✓':'Data Matrix не поддерживается браузером'}{lastCandidate?` · ${lastCandidate.format}`:''}</div>}</div></div>;
}
