import React,{useEffect,useRef,useState}from'react';
import{Camera,X,ScanLine,Package,Save}from'lucide-react';
import{findProductByCode,getCategories,saveProduct}from'./services/productStore';

const WANTED=['ean_13','ean_8','upc_a','upc_e','code_128','code_39','itf'];

export default function BarcodeScanner({onDetected,onClose}){
 const videoRef=useRef(null),streamRef=useRef(null),timerRef=useRef(null),busyRef=useRef(false),detectedRef=useRef(false),onDetectedRef=useRef(onDetected);
 const[error,setError]=useState(''),[ready,setReady]=useState(false),[unknownCode,setUnknownCode]=useState(''),[draft,setDraft]=useState(null),[saving,setSaving]=useState(false);
 useEffect(()=>{onDetectedRef.current=onDetected},[onDetected]);
 useEffect(()=>{let alive=true;const stop=()=>{if(timerRef.current){clearInterval(timerRef.current);timerRef.current=null}streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null};
  (async()=>{try{
   if(!navigator.mediaDevices?.getUserMedia)throw new Error('Камера недоступна. Откройте CIA POS через HTTPS или Android-приложение.');
   if(!('BarcodeDetector'in globalThis))throw new Error('Сканер штрихкодов не поддерживается этим браузером.');
   const supported=await globalThis.BarcodeDetector.getSupportedFormats();const formats=WANTED.filter(x=>supported.includes(x));if(!formats.length)throw new Error('EAN/UPC сканирование не поддерживается на этом устройстве.');
   const detector=new globalThis.BarcodeDetector({formats});const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});
   if(!alive){stream.getTracks().forEach(t=>t.stop());return}streamRef.current=stream;const video=videoRef.current;if(!video){stop();return}video.srcObject=stream;await video.play();if(!alive)return;setReady(true);
   timerRef.current=setInterval(async()=>{if(!alive||detectedRef.current||busyRef.current||!videoRef.current||videoRef.current.readyState<2)return;busyRef.current=true;try{const codes=await detector.detect(videoRef.current);const value=String(codes?.[0]?.rawValue||'').trim();if(value&&!detectedRef.current){detectedRef.current=true;stop();const found=findProductByCode(value);if(found){onDetectedRef.current?.(value)}else{setUnknownCode(value);setReady(false)}}}catch{}finally{busyRef.current=false}},220);
  }catch(e){if(alive){setReady(false);setError(e?.message||'Не удалось открыть камеру')}}})();
  return()=>{alive=false;stop()};
 },[]);
 const startCreate=()=>{const cats=getCategories();setDraft({productCode:unknownCode,barcode:unknownCode,name:'',price:'',category:cats[0]||'Без категории',adgCode:'',unit:'հատ',department:1,markingRequired:false,active:true,emoji:'📦',hasImage:false})};
 const save=()=>{if(!draft)return;setSaving(true);setError('');try{const saved=saveProduct({...draft,price:Number(String(draft.price).replace(',','.'))});window.dispatchEvent(new CustomEvent('cia-pos-products-changed',{detail:{product:saved}}));onDetectedRef.current?.(saved.barcode||saved.productCode)}catch(e){setError(e.message||'Не удалось сохранить товар');setSaving(false)}};
 if(draft)return <div className="barcode-scanner-bg"><div className="barcode-scanner barcode-quick-product"><div className="barcode-scanner-head"><span><Package/> Новый товар</span><button type="button" onClick={onClose}><X/></button></div><div className="barcode-quick-code"><small>Штрихкод</small><strong>{unknownCode}</strong></div><div className="barcode-quick-form"><label><span>Название *</span><input autoFocus value={draft.name} onChange={e=>setDraft(d=>({...d,name:e.target.value}))}/></label><label><span>Цена, ֏ *</span><input inputMode="decimal" value={draft.price} onChange={e=>setDraft(d=>({...d,price:e.target.value}))}/></label><label><span>Категория</span><input value={draft.category} onChange={e=>setDraft(d=>({...d,category:e.target.value}))}/></label><label><span>ԱՏԳ</span><input inputMode="numeric" value={draft.adgCode} onChange={e=>setDraft(d=>({...d,adgCode:e.target.value.replace(/\D/g,'')}))}/></label></div>{error&&<div className="barcode-quick-error">{error}</div>}<div className="barcode-quick-actions"><button type="button" onClick={onClose}>Отмена</button><button type="button" className="primary" disabled={saving||!draft.name.trim()||draft.price===''} onClick={save}><Save/>{saving?'Сохраняем…':'Сохранить и добавить в чек'}</button></div></div></div>;
 if(unknownCode)return <div className="barcode-scanner-bg"><div className="barcode-scanner barcode-not-found"><div className="barcode-scanner-head"><span><ScanLine/> Штрихкод считан</span><button type="button" onClick={onClose}><X/></button></div><div className="barcode-not-found-body"><Package/><h2>Товар не найден</h2><p>Штрихкод <strong>{unknownCode}</strong> отсутствует в каталоге.</p><button type="button" onClick={startCreate}>Создать товар</button><button type="button" className="secondary" onClick={onClose}>Отмена</button></div></div></div>;
 return <div className="barcode-scanner-bg"><div className="barcode-scanner"><div className="barcode-scanner-head"><span><ScanLine/> Сканировать штрихкод</span><button type="button" onClick={onClose}><X/></button></div><div className="barcode-camera"><video ref={videoRef} playsInline muted autoPlay/><div className="barcode-frame"><i/><i/><i/><i/></div>{!ready&&!error&&<div className="barcode-camera-state"><Camera/>Открываем камеру…</div>}{error&&<div className="barcode-camera-state error">{error}</div>}</div><p>{error?'Закройте окно и проверьте разрешение камеры.':'Наведите камеру на EAN/UPC штрихкод товара'}</p></div></div>
}
