import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Search,Minus,Plus,Banknote,CreditCard,QrCode,ReceiptText,BarChart3,Package,Settings,CheckCircle2,X,Menu,ChevronLeft,Printer,MoreHorizontal,Trash2,ShoppingBag,Users,ScanLine,WalletCards,Armchair,Store,UtensilsCrossed}from'lucide-react';
import PrinterSettings from'./PrinterSettings';
import ShiftPanel from'./ShiftPanel';
import{printPrecheck}from'./services/escposPrinter';
import{getActiveShift,recordSale}from'./services/shiftStore';
import'./styles.css';
import'./mixed-payment.css';

const PRODUCTS=[{id:1,name:'Американо',price:900,category:'Кофе',emoji:'☕'},{id:2,name:'Капучино',price:1200,category:'Кофе',emoji:'🥛'},{id:3,name:'Латте',price:1400,category:'Кофе',emoji:'🧋'},{id:4,name:'Вода',price:500,category:'Напитки',emoji:'💧'},{id:5,name:'Кола 0.5',price:700,category:'Напитки',emoji:'🥤'},{id:6,name:'Круассан',price:1000,category:'Еда',emoji:'🥐'},{id:7,name:'Сэндвич',price:2200,category:'Еда',emoji:'🥪'},{id:8,name:'Чизкейк',price:1800,category:'Десерты',emoji:'🍰'}];
const seedTables=[{id:1,hall:'Main',status:'open',guests:2,total:8800,time:'00:24'},{id:2,hall:'Main',status:'free'},{id:3,hall:'Main',status:'precheck',guests:2,total:6200,time:'01:15'},{id:4,hall:'Main',status:'free'},{id:5,hall:'Main',status:'free'},{id:6,hall:'Main',status:'open',guests:4,total:12500,time:'00:48'},{id:7,hall:'Main',status:'reserved',time:'19:00'},{id:8,hall:'Main',status:'free'},{id:9,hall:'Main',status:'free'},{id:10,hall:'Терраса',status:'free'},{id:11,hall:'Терраса',status:'open',guests:3,total:7400,time:'00:31'},{id:12,hall:'Терраса',status:'free'},{id:20,hall:'VIP',status:'free'},{id:21,hall:'VIP',status:'reserved',time:'20:00'}];
const fmt=v=>new Intl.NumberFormat('ru-RU').format(v||0)+' ֏';
const savedPrinters=()=>{try{return JSON.parse(localStorage.getItem('cia-pos-printers')||'[]')}catch{return[]}};
const readLocal=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}};

function App(){
 const savedMode=localStorage.getItem('cia-pos-mode');
 const[mode,setMode]=useState(savedMode||'restaurant'),[modePicker,setModePicker]=useState(!savedMode),[settingsOpen,setSettingsOpen]=useState(false),[shiftOpen,setShiftOpen]=useState(false),[activeShift,setActiveShift]=useState(()=>getActiveShift()),[tables,setTables]=useState(()=>readLocal('cia-pos-tables',seedTables)),[orders,setOrders]=useState(()=>readLocal('cia-pos-table-orders',{})),[hall,setHall]=useState('Main'),[screen,setScreen]=useState(savedMode==='shop'?'order':'tables'),[tableId,setTableId]=useState(null),[newTable,setNewTable]=useState(null),[guests,setGuests]=useState(2),[cart,setCart]=useState({}),[query,setQuery]=useState(''),[category,setCategory]=useState('Все'),[catalogOpen,setCatalogOpen]=useState(false),[paymentOpen,setPaymentOpen]=useState(false),[paymentType,setPaymentType]=useState('cash'),[mixedCash,setMixedCash]=useState(''),[success,setSuccess]=useState(false),[serviceEnabled,setServiceEnabled]=useState(true),[printing,setPrinting]=useState(false);
 useEffect(()=>localStorage.setItem('cia-pos-mode',mode),[mode]);
 useEffect(()=>localStorage.setItem('cia-pos-tables',JSON.stringify(tables)),[tables]);
 useEffect(()=>localStorage.setItem('cia-pos-table-orders',JSON.stringify(orders)),[orders]);
 const categories=useMemo(()=>['Все',...new Set(PRODUCTS.map(p=>p.category))],[]),filtered=PRODUCTS.filter(p=>(category==='Все'||p.category===category)&&(!query||p.name.toLowerCase().includes(query.toLowerCase()))),lines=Object.values(cart),subtotal=lines.reduce((s,i)=>s+i.qty*i.price,0),service=mode==='restaurant'&&serviceEnabled?Math.round(subtotal*.1):0,total=subtotal+service;
 const switchMode=m=>{setMode(m);setModePicker(false);setCart({});setTableId(null);setNewTable(null);setPaymentOpen(false);setCatalogOpen(false);setScreen(m==='restaurant'?'tables':'order')};
 const openTable=t=>{if(t.status==='free'){setNewTable(t);setGuests(2);return}const order=orders[t.id];setTableId(t.id);setGuests(order?.guests||t.guests||2);setCart(order?.cart||{});setServiceEnabled(order?.serviceEnabled!==false);setScreen('order')};
 const createOrder=()=>{const id=newTable.id;setTables(ts=>ts.map(t=>t.id===id?{...t,status:'open',guests,total:0,time:'00:00'}:t));setOrders(os=>({...os,[id]:{guests,cart:{},serviceEnabled:true}}));setTableId(id);setCart({});setNewTable(null);setScreen('order')};
 const add=p=>setCart(c=>({...c,[p.id]:{...p,qty:(c[p.id]?.qty||0)+1}}));
 const qty=(id,d)=>setCart(c=>{const n={...c},q=(n[id]?.qty||0)+d;if(q<=0)delete n[id];else n[id]={...n[id],qty:q};return n});
 useEffect(()=>{if(mode!=='restaurant'||tableId===null||screen!=='order')return;setOrders(os=>({...os,[tableId]:{guests,cart,serviceEnabled}}));setTables(ts=>ts.map(t=>t.id===tableId?{...t,guests,total}:t))},[cart,guests,serviceEnabled,mode,tableId,screen,total]);
 const doPrecheck=async()=>{if(!total||mode!=='restaurant'||printing)return;const printer=savedPrinters().find(p=>p.precheck&&p.verified);if(!printer){alert('Нет проверенного принтера для пречека. Откройте Ещё → Принтеры, выполните тестовую печать и включите роль «Пречек».');setSettingsOpen(true);return}setPrinting(true);try{await printPrecheck(printer,{businessName:'CIA POS LITE',receiptNo:`T${tableId}-${Date.now().toString().slice(-6)}`,items:lines,subtotal,serviceAmount:service,total,cashier:'Касса №1'});setTables(ts=>ts.map(t=>t.id===tableId?{...t,status:'precheck',guests,total}:t))}catch(e){alert(e.message||'Не удалось напечатать пречек. Стол оставлен открытым.')}finally{setPrinting(false)}};
 const pay=()=>{if(!total)return;const shift=getActiveShift();if(!shift){setPaymentOpen(false);setShiftOpen(true);alert('Смена закрыта. Откройте смену перед первой продажей.');return}const cash=paymentType==='mixed'?Number(mixedCash||0):paymentType==='cash'?total:0;const payments=paymentType==='mixed'?{cash,card:total-cash,qr:0}:null;try{const nextShift=recordSale({total,subtotal,serviceRate:service?10:0,serviceAmount:service,paymentType,payments,mode,items:lines,tableId});setActiveShift(nextShift)}catch(e){alert(e.message||'Не удалось записать продажу в смену.');return}setPaymentOpen(false);setMixedCash('');if(mode==='restaurant'&&tableId!==null){setOrders(os=>{const next={...os};delete next[tableId];return next});setTables(ts=>ts.map(t=>t.id===tableId?{...t,status:'free',guests:null,total:null,time:null}:t))}setSuccess(true);setTimeout(()=>{setSuccess(false);setCart({});if(mode==='restaurant'){setTableId(null);setScreen('tables')}else setScreen('order')},1200)};
 const title=mode==='shop'?'Новая продажа':`Стол ${tableId||''}`;
 return <div className="cia-app"><header className="cia-topbar"><button className="top-icon" onClick={()=>setSettingsOpen(true)}><Menu/></button><div className="cia-logo"><strong>CIA POS</strong><span>light</span></div><button className="mode-chip" onClick={()=>setModePicker(true)}>{mode==='shop'?<Store/>:<UtensilsCrossed/>}{mode==='shop'?'Магазин':'Ресторан'}</button><div className="online-state"><i/> {activeShift?'Смена открыта':'Смена закрыта'}</div></header>
 {mode==='restaurant'&&screen==='tables'?<main className="floor"><div className="floor-head"><div><span className="kicker">Ресторан</span><h1>Выберите стол</h1></div><button className="new-order"><Plus/> Новый заказ</button></div><div className="hall-tabs">{['Main','Терраса','VIP'].map(h=><button key={h} className={hall===h?'active':''} onClick={()=>setHall(h)}>{h}</button>)}</div><div className="table-grid">{tables.filter(t=>t.hall===hall).map(t=><button key={t.id} onClick={()=>openTable(t)} className={'table-card '+t.status}><strong>{t.id}</strong>{t.status==='free'&&<span>Свободен</span>}{t.status==='open'&&<><span>{t.guests} гостя · {t.time}</span><b>{fmt(t.total)}</b></>}{t.status==='precheck'&&<><span>Пречек · {t.time}</span><b>{fmt(t.total)}</b></>}{t.status==='reserved'&&<><span>Бронь</span><b>{t.time}</b></>}</button>)}</div><div className="legend"><span><i className="free"/>Свободен</span><span><i className="open"/>Открыт заказ</span><span><i className="precheck"/>Пречек</span><span><i className="reserved"/>Бронь</span></div></main>:
 <div className={'workspace '+(mode==='shop'?'shop-workspace':'')}><section className="receipt-side"><div className="order-toolbar">{mode==='restaurant'?<button onClick={()=>setScreen('tables')}><ChevronLeft/> Столы</button>:<span className="shop-label"><Store/> Магазин</span>}<b>{title}</b>{mode==='restaurant'?<span><Users size={18}/> {guests}</span>:<span>Касса №1</span>}</div>{mode==='restaurant'&&<div className="receipt-tabs"><button className="active">Чек</button><button>Гости</button><button>Комментарий</button></div>}<div className="receipt-title-row"><div><span className="kicker">{mode==='shop'?'Продажа':'Открытый заказ'}</span><h1>{title}</h1></div><button className="round-danger" onClick={()=>setCart({})}><Trash2/></button></div><div className={'guest-card '+(mode==='shop'?'shop-card':'')}><div className="guest-head"><span>{mode==='shop'?'ТОВАРЫ':'ГОСТЬ 1'}</span><span>{lines.length} поз.</span></div>{lines.length===0?<div className="empty-check"><ShoppingBag/><b>{mode==='shop'?'Чек пуст':'Заказ пуст'}</b><span>Добавьте товары</span></div>:lines.map(i=><div className="receipt-line" key={i.id}><div className="item-name"><div className="mini-art">{i.emoji}</div><div><b>{i.name}</b><small>{i.category}</small></div></div><div className="qty-stepper"><button onClick={()=>qty(i.id,-1)}><Minus/></button><b>{i.qty}</b><button onClick={()=>qty(i.id,1)}><Plus/></button></div><span className="unit-price">{fmt(i.price)}</span><b className="row-total">{fmt(i.price*i.qty)}</b></div>)}</div><button className="add-product" onClick={()=>setCatalogOpen(true)}><Plus/> Добавить товар</button>{mode==='restaurant'&&<div className="bill-options"><label className="service-toggle"><span><b>Обслуживание 10%</b><small>Сервисный сбор</small></span><input type="checkbox" checked={serviceEnabled} onChange={e=>setServiceEnabled(e.target.checked)}/><i/></label></div>}<div className="totals-block"><div><span>Сумма</span><b>{fmt(subtotal)}</b></div>{service>0&&<div><span>Обслуживание 10%</span><b>{fmt(service)}</b></div>}<div className="to-pay"><span>Итого</span><strong>{fmt(total)}</strong></div></div><div className={'checkout-row '+(mode==='shop'?'shop-checkout':'')}><button className="square-action" onClick={()=>setSettingsOpen(true)}><MoreHorizontal/></button>{mode==='restaurant'&&<button className="precheck-main" disabled={!total||printing} onClick={doPrecheck}><Printer/> {printing?'Печать...':'Пречек'}</button>}<button className="pay-main" disabled={!total} onClick={()=>setPaymentOpen(true)}>Оплатить</button></div></section>
 <aside className={'catalog-side '+(catalogOpen?'mobile-open':'')}><div className="catalog-top"><div><span className="kicker">{mode==='shop'?'Каталог':'Меню'}</span><h2>Все товары</h2></div><button className="catalog-close" onClick={()=>setCatalogOpen(false)}><X/></button></div><div className="search-box"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск товара или штрихкода"/><ScanLine/></div><div className="category-strip">{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="product-cards">{filtered.map(p=><button key={p.id} className="catalog-card" onClick={()=>add(p)}><div className="product-visual">{p.emoji}</div><div><b>{p.name}</b><span>{fmt(p.price)}</span></div><em><Plus/></em></button>)}</div></aside></div>}
 {modePicker&&<div className="modal-bg"><div className="mode-modal"><span className="kicker">CIA POS Light</span><h2>Режим работы</h2><p>Можно изменить позже.</p><button className={mode==='shop'?'selected':''} onClick={()=>switchMode('shop')}><Store/><span><b>Магазин</b><small>Быстрая продажа без столов и гостей</small></span></button><button className={mode==='restaurant'?'selected':''} onClick={()=>switchMode('restaurant')}><UtensilsCrossed/><span><b>Ресторан</b><small>Столы, гости, пречек и обслуживание</small></span></button></div></div>}
 {newTable&&<div className="modal-bg"><div className="new-order-modal"><button className="modal-x" onClick={()=>setNewTable(null)}><X/></button><span className="kicker">Новый заказ</span><h2>Стол {newTable.id}</h2><p>Количество гостей</p><div className="guest-counter"><button onClick={()=>setGuests(Math.max(1,guests-1))}><Minus/></button><strong>{guests}</strong><button onClick={()=>setGuests(guests+1)}><Plus/></button></div><button className="create-order" onClick={createOrder}>Создать заказ</button></div></div>}
 {paymentOpen&&<div className="payment-screen"><div className="payment-sheet"><div className="payment-toolbar"><button onClick={()=>setPaymentOpen(false)}><ChevronLeft/>Отменить</button><span>Оплата{mode==='restaurant'?` · Стол ${tableId}`:''}</span><i/></div><div className="payment-content"><p>К оплате</p><h2>{fmt(total)}</h2><div className="payment-list"><button className={paymentType==='cash'?'selected':''} onClick={()=>setPaymentType('cash')}><Banknote/><span>Наличными</span><b>{paymentType==='cash'?fmt(total):'0 ֏'}</b></button><button className={paymentType==='card'?'selected':''} onClick={()=>setPaymentType('card')}><CreditCard/><span>Карточкой</span><b>{paymentType==='card'?fmt(total):'0 ֏'}</b></button><button className={paymentType==='qr'?'selected':''} onClick={()=>setPaymentType('qr')}><QrCode/><span>IDRAM / QR</span><b>{paymentType==='qr'?fmt(total):'0 ֏'}</b></button>{mode==='restaurant'&&<button className={paymentType==='mixed'?'selected':''} onClick={()=>setPaymentType('mixed')}><WalletCards/><span>Смешанная</span><b>{paymentType==='mixed'?`${fmt(Number(mixedCash||0))} наличными`:'0 ֏'}</b></button>}{paymentType==='mixed'&&<label className="mixed-payment-input">Наличными<input inputMode="numeric" value={mixedCash} onChange={e=>setMixedCash(e.target.value.replace(/[^0-9]/g,''))} placeholder="0"/><small>Картой: {fmt(Math.max(0,total-Number(mixedCash||0)))}</small></label>}</div><button className="confirm-pay" disabled={paymentType==='mixed'&&Number(mixedCash||0)>total} onClick={pay}>Оплатить {fmt(total)}</button></div></div></div>}
 {success&&<div className="success-overlay"><div><CheckCircle2/><h2>Оплата успешна</h2><p>{mode==='restaurant'?'Стол освобождён':'Продажа завершена'}</p></div></div>}
 {settingsOpen&&<div className="settings-overlay"><PrinterSettings onBack={()=>setSettingsOpen(false)}/></div>}
 {shiftOpen&&<div className="shift-overlay"><ShiftPanel onBack={()=>setShiftOpen(false)} onShiftChange={setActiveShift}/></div>}
 <nav className="bottom-nav">{mode==='restaurant'&&<button className={screen==='tables'?'active':''} onClick={()=>setScreen('tables')}><Armchair/><span>Столы</span></button>}<button className={mode==='shop'?'active':''} onClick={()=>{if(mode==='shop')setScreen('order');else if(screen==='order')setCatalogOpen(true)}}><ReceiptText/><span>{mode==='shop'?'Продажа':'Чек'}</span></button><button onClick={()=>setCatalogOpen(true)}><Package/><span>Товары</span></button><button onClick={()=>setShiftOpen(true)}><BarChart3/><span>Смена</span></button><button onClick={()=>setSettingsOpen(true)}><Settings/><span>Ещё</span></button></nav></div>}
createRoot(document.getElementById('root')).render(<App/>);
