import React,{useEffect,useMemo,useState}from'react';
import{ChevronLeft,Printer,Plus,RefreshCw,Wifi,CheckCircle2,AlertCircle,Trash2,Package,Settings,Languages}from'lucide-react';
import{discoverPrinters,isNativePrinterAvailable,printTest}from'./services/escposPrinter';
import ProductBackoffice from'./ProductBackoffice';
import LanguageSwitcher from'./LanguageSwitcher';
import'./product-backoffice.css';

const STORAGE_KEY='cia-pos-printers';
const blankPrinter=()=>({id:`printer-${Date.now()}`,name:'ESC/POS принтер',ip:'',port:9100,paper:'80',autoCut:true,precheck:true,bar:false,kitchen:false,verified:false});
const readPrinters=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}};
const persist=list=>localStorage.setItem(STORAGE_KEY,JSON.stringify(list));

export default function PrinterSettings({onBack}){
 const[page,setPage]=useState('home');
 if(page==='products')return <ProductBackoffice onBack={()=>setPage('home')}/>;
 if(page==='printers')return <PrinterManager onBack={()=>setPage('home')}/>;
 return <div className="devices-page"><div className="devices-toolbar"><button className="back-button" onClick={onBack}><ChevronLeft/> Назад</button><h1>Ещё</h1><span className="toolbar-spacer"/></div><div className="devices-card"><div className="section-label">УПРАВЛЕНИЕ</div><button className="device-row" onClick={()=>setPage('products')}><span className="device-icon"><Package/></span><span className="device-info"><strong>Товары</strong><span>Каталог, цены, штрихкоды, ԱՏԳ и маркировка</span></span></button><button className="device-row" onClick={()=>setPage('printers')}><span className="device-icon"><Printer/></span><span className="device-info"><strong>Принтеры</strong><span>ESC/POS · LAN · роли печати</span></span></button><div className="device-row"><span className="device-icon"><Languages/></span><span className="device-info"><strong>Язык интерфейса</strong><span>Русский · Հայերեն · English</span></span><LanguageSwitcher settings compact/></div><div className="device-row"><span className="device-icon"><Settings/></span><span className="device-info"><strong>Настройки</strong><span>Дополнительные параметры будут добавлены позже</span></span></div></div></div>;
}

function PrinterManager({onBack}){
 const[printers,setPrinters]=useState(readPrinters),[selectedId,setSelectedId]=useState(null),[draft,setDraft]=useState(null),[searching,setSearching]=useState(false),[testing,setTesting]=useState(false),[notice,setNotice]=useState('');
 const native=isNativePrinterAvailable();
 const selected=useMemo(()=>printers.find(p=>p.id===selectedId)||null,[printers,selectedId]);
 useEffect(()=>{if(selected)setDraft({...selected})},[selectedId]);
 const message=text=>{setNotice(text);setTimeout(()=>setNotice(''),2600)};
 const openNew=()=>{setSelectedId(null);setDraft(blankPrinter())};
 const update=(key,value)=>setDraft(d=>({...d,[key]:value,verified:key==='ip'||key==='port'?false:d.verified}));
 const save=()=>{if(!draft?.ip.trim())return message('Укажите IP-адрес принтера');const normalized={...draft,ip:draft.ip.trim(),port:Number(draft.port)||9100,paper:String(draft.paper||'80')};const next=printers.some(p=>p.id===normalized.id)?printers.map(p=>p.id===normalized.id?normalized:p):[...printers,normalized];setPrinters(next);persist(next);setSelectedId(normalized.id);setDraft(normalized);message('Настройки принтера сохранены')};
 const remove=()=>{if(!draft)return;const next=printers.filter(p=>p.id!==draft.id);setPrinters(next);persist(next);setDraft(null);setSelectedId(null);message('Принтер удалён')};
 const discover=async()=>{if(!native)return message('Поиск LAN-принтеров доступен в Android-приложении');setSearching(true);try{const savedPorts=printers.map(p=>Number(p.port)).filter(Boolean);const found=await discoverPrinters({ports:savedPorts});if(!found.length)return message('ESC/POS-принтеры в LAN не найдены');const merged=[...printers];found.forEach((p,i)=>{if(!merged.some(x=>x.ip===p.ip&&Number(x.port)===Number(p.port)))merged.push({...blankPrinter(),...p,id:`lan-${p.ip}-${p.port}`,name:p.name||`ESC/POS ${i+1}`})});setPrinters(merged);persist(merged);message(`Найдено: ${found.length}`)}catch(e){message(e.message||'Ошибка поиска принтеров')}finally{setSearching(false)}};
 const test=async()=>{if(!draft?.ip.trim())return message('Укажите IP-адрес принтера');if(!native)return message('Тестовая печать доступна в Android-приложении');setTesting(true);try{await printTest(draft);const checked={...draft,verified:true};setDraft(checked);const next=printers.some(p=>p.id===checked.id)?printers.map(p=>p.id===checked.id?checked:p):[...printers,checked];setPrinters(next);persist(next);setSelectedId(checked.id);message('Данные теста отправлены. Проверьте бумажный чек.')}catch(e){const failed={...draft,verified:false};setDraft(failed);const next=printers.map(p=>p.id===failed.id?failed:p);setPrinters(next);persist(next);message(e.message||'Не удалось отправить тест')}finally{setTesting(false)}};
 if(draft)return <div className="devices-page"><div className="devices-toolbar"><button className="back-button" onClick={()=>{setDraft(null);setSelectedId(null)}}><ChevronLeft/> Принтеры</button><h1>Настройка принтера</h1><span className="toolbar-spacer"/></div><div className="printer-settings-card"><div className="printer-title-row"><div><div className="printer-name-line"><Printer/><input className="printer-name-input" value={draft.name} onChange={e=>update('name',e.target.value)}/></div><p>{draft.verified?'Проверен тестовой печатью':'Не проверен'}</p></div>{draft.verified?<CheckCircle2 color="#22c55e"/>:<AlertCircle color="#f59e0b"/>}</div><div className="connection-grid"><label>IP-адрес<input inputMode="decimal" value={draft.ip} placeholder="192.168.1.100" onChange={e=>update('ip',e.target.value)}/></label><label>Порт<input inputMode="numeric" value={draft.port} onChange={e=>update('port',e.target.value)}/></label><label>Бумага<select value={draft.paper} onChange={e=>update('paper',e.target.value)}><option value="80">80 мм</option><option value="58">58 мм</option></select></label></div><div className="settings-section"><h3>Назначение</h3>{[['precheck','Пречек','Печать предварительного счёта'],['bar','Бар','Напитки и барные заказы'],['kitchen','Кухня','Кухонные заказы']].map(([key,title,desc])=><div className="setting-row" key={key}><span><strong>{title}</strong><small>{desc}</small></span><button className={'switch '+(draft[key]?'on':'')} onClick={()=>update(key,!draft[key])}><span/></button></div>)}<div className="setting-row"><span><strong>Автообрезка</strong><small>Обрезать бумагу после печати</small></span><button className={'switch '+(draft.autoCut?'on':'')} onClick={()=>update('autoCut',!draft.autoCut)}><span/></button></div></div><button className="outline-action" disabled={testing} onClick={test}><Printer/> {testing?'Печать...':'Тестовая печать'}</button><button className="primary-action" onClick={save}>Сохранить принтер</button>{printers.some(p=>p.id===draft.id)&&<button className="danger-action" onClick={remove}><Trash2/>Удалить принтер</button>} {!native&&<div className="native-note"><AlertCircle/><span>В браузере можно сохранить IP и настройки. Поиск в LAN и реальная ESC/POS печать работают в Android-приложении CIA POS.</span></div>}</div>{notice&&<div className="device-toast">{notice}</div>}</div>;
 return <div className="devices-page"><div className="devices-toolbar"><button className="back-button" onClick={onBack}><ChevronLeft/> Назад</button><h1>Принтеры</h1><span className="toolbar-spacer"/></div><div className="devices-card"><div className="section-label">ESC/POS · LAN</div>{printers.length===0?<div className="no-devices"><Wifi size={40}/><strong>Принтеры не добавлены</strong><span>Найдите ESC/POS принтер в локальной сети или добавьте его IP вручную.</span></div>:printers.map(p=><button className="device-row" key={p.id} onClick={()=>{setSelectedId(p.id);setDraft({...p})}}><span className="device-icon"><Printer/></span><span className="device-info"><strong>{p.name}</strong><span><i className={'dot '+(p.verified?'online':'')}/>{p.ip}:{p.port} · {p.paper} мм {p.verified?'· проверен':'· не проверен'}</span></span></button>)}<div className="device-actions"><button onClick={discover} disabled={searching}><RefreshCw/> {searching?'Поиск...':'Найти в LAN'}</button><button onClick={openNew}><Plus/> Добавить вручную</button></div></div>{!native&&<div className="web-device-info">На веб-версии доступна ручная настройка. Автопоиск и тестовая печать требуют Android-приложение.</div>}{notice&&<div className="device-toast">{notice}</div>}</div>;
}
