import React,{useEffect,useMemo,useState}from'react';
import{ChevronLeft,Printer,Plus,RefreshCw,Wifi,CheckCircle2,AlertCircle,Trash2,Package,Settings,Languages,Warehouse,ShieldCheck}from'lucide-react';
import{discoverPrinters,isNativePrinterAvailable,printTest}from'./services/escposPrinter';
import ProductBackoffice from'./ProductBackoffice';
import StockBackoffice from'./StockBackoffice';
import CashierSettings from'./CashierSettings';
import LanguageSwitcher from'./LanguageSwitcher';
import{useLanguage}from'./services/i18n';
import'./product-backoffice.css';
const STORAGE_KEY='cia-pos-printers';
const blankPrinter=()=>({id:`printer-${Date.now()}`,name:'ESC/POS',ip:'',port:9100,paper:'80',autoCut:true,precheck:true,bar:false,kitchen:false,verified:false});
const readPrinters=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}};const persist=list=>localStorage.setItem(STORAGE_KEY,JSON.stringify(list));
export default function PrinterSettings({onBack}){const{t}=useLanguage();const[page,setPage]=useState('home');useEffect(()=>{if(localStorage.getItem('cia-pos-pending-barcode'))setPage('products')},[]);if(page==='products')return <ProductBackoffice onBack={()=>setPage('home')}/>;if(page==='stock')return <StockBackoffice onBack={()=>setPage('home')}/>;if(page==='printers')return <PrinterManager onBack={()=>setPage('home')}/>;if(page==='admin')return <CashierSettings onBack={()=>setPage('home')}/>;return <div className="devices-page"><div className="devices-toolbar"><button className="back-button" onClick={onBack}><ChevronLeft/> {t('back')}</button><h1>{t('more')}</h1><span className="toolbar-spacer"/></div><div className="devices-card"><div className="section-label">{t('management')}</div><button className="device-row" onClick={()=>setPage('products')}><span className="device-icon"><Package/></span><span className="device-info"><strong>{t('products')}</strong><span>{t('productsDesc')}</span></span></button><button className="device-row" onClick={()=>setPage('stock')}><span className="device-icon"><Warehouse/></span><span className="device-info"><strong>Склад и поставки</strong><span>Остатки, поступления и движения товаров</span></span></button><button className="device-row" onClick={()=>setPage('printers')}><span className="device-icon"><Printer/></span><span className="device-info"><strong>{t('printers')}</strong><span>{t('printersDesc')}</span></span></button><button className="device-row" onClick={()=>setPage('admin')}><span className="device-icon"><ShieldCheck/></span><span className="device-info"><strong>Администратор</strong><span>Имя и PIN для входа в кассу</span></span></button><div className="device-row"><span className="device-icon"><Languages/></span><span className="device-info"><strong>{t('interfaceLanguage')}</strong><span>{t('languageDesc')}</span></span><LanguageSwitcher settings compact/></div><div className="device-row"><span className="device-icon"><Settings/></span><span className="device-info"><strong>{t('settings')}</strong><span>{t('settingsDesc')}</span></span></div></div></div>}
function PrinterManager({onBack}){const{t}=useLanguage();const[printers,setPrinters]=useState(readPrinters),[selectedId,setSelectedId]=useState(null),[draft,setDraft]=useState(null),[searching,setSearching]=useState(false),[testing,setTesting]=useState(false),[notice,setNotice]=useState('');const native=isNativePrinterAvailable(),selected=useMemo(()=>printers.find(p=>p.id===selectedId)||null,[printers,selectedId]);useEffect(()=>{if(selected)setDraft({...selected})},[selectedId]);const message=text=>{setNotice(text);setTimeout(()=>setNotice(''),2600)},openNew=()=>{setSelectedId(null);setDraft(blankPrinter())},update=(key,value)=>setDraft(d=>({...d,[key]:value,verified:key==='ip'||key==='port'?false:d.verified}));
 const save=()=>{if(!draft?.ip.trim())return message(t('enterPrinterIp'));const normalized={...draft,ip:draft.ip.trim(),port:Number(draft.port)||9100,paper:String(draft.paper||'80')},next=printers.some(p=>p.id===normalized.id)?printers.map(p=>p.id===normalized.id?normalized:p):[...printers,normalized];setPrinters(next);persist(next);setSelectedId(normalized.id);setDraft(normalized);message(t('printerSaved'))};const remove=()=>{if(!draft)return;const next=printers.filter(p=>p.id!==draft.id);setPrinters(next);persist(next);setDraft(null);setSelectedId(null);message(t('printerDeleted'))};
 const discover=async()=>{if(!native)return message(t('lanAndroidOnly'));setSearching(true);try{const savedPorts=printers.map(p=>Number(p.port)).filter(Boolean),found=await discoverPrinters({ports:savedPorts});if(!found.length)return message(t('printersNotFound'));const merged=[...printers];found.forEach((p,i)=>{if(!merged.some(x=>x.ip===p.ip&&Number(x.port)===Number(p.port)))merged.push({...blankPrinter(),...p,id:`lan-${p.ip}-${p.port}`,name:p.name||`ESC/POS ${i+1}`})});setPrinters(merged);persist(merged);message(`${t('found')}: ${found.length}`)}catch(e){message(e.message||t('searchError'))}finally{setSearching(false)}};
 const test=async()=>{if(!draft?.ip.trim())return message(t('enterPrinterIp'));if(!native)return message(t('testAndroidOnly'));setTesting(true);try{await printTest(draft);const checked={...draft,verified:true};setDraft(checked);const next=printers.some(p=>p.id===checked.id)?printers.map(p=>p.id===checked.id?checked:p):[...printers,checked];setPrinters(next);persist(next);setSelectedId(checked.id);message(t('testSent'))}catch(e){const failed={...draft,verified:false};setDraft(failed);setPrinters(printers.map(p=>p.id===failed.id?failed:p));message(e.message||t('testFailed'))}finally{setTesting(false)}};
 if(draft)return <div className="devices-page"><div className="devices-toolbar"><button className="back-button" onClick={()=>{setDraft(null);setSelectedId(null)}}><ChevronLeft/> {t('printers')}</button><h1>{t('printerSetup')}</h1><span className="toolbar-spacer"/></div><div className="printer-settings-card"><div className="printer-title-row"><div><div className="printer-name-line"><Printer/><input className="printer-name-input" value={draft.name} onChange={e=>update('name',e.target.value)}/></div><p>{t(draft.verified?'verified':'notVerified')}</p></div>{draft.verified?<CheckCircle2 color="#22c55e"/>:<AlertCircle color="#f59e0b"/>}</div><div className="connection-grid"><label>{t('ipAddress')}<input inputMode="decimal" value={draft.ip} placeholder="192.168.1.100" onChange={e=>update('ip',e.target.value)}/></label><label>{t('port')}<input inputMode="numeric" value={draft.port} onChange={e=>update('port',e.target.value)}/></label><label>{t('paper')}<select value={draft.paper} onChange={e=>update('paper',e.target.value)}><option value="80">80 mm</option><option value="58">58 mm</option></select></label></div><div className="settings-section"><h3>{t('assignment')}</h3>{[['precheck','precheck','precheckDesc'],['bar','bar','barDesc'],['kitchen','kitchen','kitchenDesc']].map(([key,title,desc])=><div className="setting-row" key={key}><span><strong>{t(title)}</strong><small>{t(desc)}</small></span><button className={'switch '+(draft[key]?'on':'')} onClick={()=>update(key,!draft[key])}><span/></button></div>)}<div className="setting-row"><span><strong>{t('autoCut')}</strong><small>{t('autoCutDesc')}</small></span><button className={'switch '+(draft.autoCut?'on':'')} onClick={()=>update('autoCut',!draft.autoCut)}><span/></button></div></div><button className="outline-action" disabled={testing} onClick={test}><Printer/> {t(testing?'printing':'testPrint')}</button><button className="primary-action" onClick={save}>{t('savePrinter')}</button>{printers.some(p=>p.id===draft.id)&&<button className="danger-action" onClick={remove}><Trash2/>{t('deletePrinter')}</button>}{!native&&<div className="native-note"><AlertCircle/><span>{t('browserPrinterNote')}</span></div>}</div>{notice&&<div className="device-toast">{notice}</div>}</div>;
 return <div className="devices-page"><div className="devices-toolbar"><button className="back-button" onClick={onBack}><ChevronLeft/> {t('back')}</button><h1>{t('printers')}</h1><span className="toolbar-spacer"/></div><div className="devices-card"><div className="section-label">ESC/POS · LAN</div>{printers.length===0?<div className="no-devices"><Wifi size={40}/><strong>{t('printersEmpty')}</strong><span>{t('printersEmptyDesc')}</span></div>:printers.map(p=><button className="device-row" key={p.id} onClick={()=>{setSelectedId(p.id);setDraft({...p})}}><span className="device-icon"><Printer/></span><span className="device-info"><strong>{p.name}</strong><span><i className={'dot '+(p.verified?'online':'')}/>{p.ip}:{p.port} · {p.paper} mm · {t(p.verified?'checked':'unchecked')}</span></span></button>)}<div className="device-actions"><button onClick={discover} disabled={searching}><RefreshCw/> {t(searching?'searching':'searchLan')}</button><button onClick={openNew}><Plus/> {t('addManual')}</button></div></div>{!native&&<div className="web-device-info">{t('webPrinterInfo')}</div>}{notice&&<div className="device-toast">{notice}</div>}</div>}
