import React,{useMemo,useState}from'react';
import{ChevronLeft,Package,Plus,Search,Pencil,Trash2,X,Save,ScanLine}from'lucide-react';
import{getProducts,getCategories,saveProduct,deleteProduct}from'./services/productStore';

const empty=()=>({productCode:'',name:'',category:'',price:'',barcode:'',adgCode:'',unit:'հատ',department:1,markingRequired:false,active:true,emoji:'📦'});
const fmt=v=>new Intl.NumberFormat('ru-RU').format(Number(v)||0)+' ֏';

export default function ProductBackoffice({onBack,onChanged}){
 const[products,setProducts]=useState(()=>getProducts()),[categories,setCategories]=useState(()=>getCategories()),[query,setQuery]=useState(''),[draft,setDraft]=useState(null),[notice,setNotice]=useState('');
 const filtered=useMemo(()=>products.filter(p=>!query||[p.name,p.productCode,p.barcode,p.adgCode].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase()))),[products,query]);
 const reload=()=>{setProducts(getProducts());setCategories(getCategories());onChanged?.()};
 const edit=p=>{setNotice('');setDraft({...p,price:String(p.price)})};
 const create=()=>{setNotice('');setDraft({...empty(),category:categories[0]||''})};
 const save=()=>{try{saveProduct(draft);setDraft(null);setNotice('Товар сохранён');reload()}catch(e){setNotice(e.message||'Не удалось сохранить товар')}};
 const remove=p=>{if(!confirm(`Удалить «${p.name}»?`))return;deleteProduct(p.id);reload()};
 return <div className="product-office">
  <div className="po-head"><button className="po-back" onClick={onBack}><ChevronLeft/>Назад</button><div><span>BACK OFFICE</span><h1>Товары</h1><p>Локальный каталог CIA POS · подготовлен для HDM</p></div><button className="po-add" onClick={create}><Plus/>Добавить товар</button></div>
  <div className="po-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Название, код товара, штрихкод или ԱՏԳ"/><ScanLine/></div>
  {notice&&<div className="po-notice">{notice}</div>}
  <div className="po-table"><div className="po-row po-columns"><span>Товар</span><span>Цена</span><span>Штрихкод</span><span>ԱՏԳ</span><span>Ед.</span><span/></div>{filtered.map(p=><div className="po-row" key={p.id}><div className="po-product"><i>{p.emoji||'📦'}</i><span><b>{p.name}</b><small>{p.category} · код {p.productCode}{p.markingRequired?' · Data Matrix':''}</small></span></div><b>{fmt(p.price)}</b><span>{p.barcode||'—'}</span><span>{p.adgCode||'—'}</span><span>{p.unit}</span><div className="po-actions"><button onClick={()=>edit(p)}><Pencil/></button><button onClick={()=>remove(p)}><Trash2/></button></div></div>)}</div>
  {draft&&<div className="po-modal-bg"><div className="po-modal"><button className="po-x" onClick={()=>setDraft(null)}><X/></button><div className="po-modal-title"><Package/><div><span>КАРТОЧКА ТОВАРА</span><h2>{draft.id?'Редактировать товар':'Новый товар'}</h2></div></div><div className="po-form"><label><span>Название *</span><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label><span>Цена, ֏ *</span><input inputMode="decimal" value={draft.price} onChange={e=>setDraft({...draft,price:e.target.value})}/></label><label><span>Код товара HDM *</span><input maxLength="50" value={draft.productCode} onChange={e=>setDraft({...draft,productCode:e.target.value})}/></label><label><span>Категория</span><input list="cia-categories" value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/><datalist id="cia-categories">{categories.map(c=><option key={c} value={c}/>)}</datalist></label><label><span>Штрихкод EAN / UPC / Code128</span><div className="po-code-input"><input value={draft.barcode} onChange={e=>setDraft({...draft,barcode:e.target.value})}/><button title="Сканер камеры будет подключён следующим этапом"><ScanLine/></button></div></label><label><span>ԱՏԳ код</span><input value={draft.adgCode} onChange={e=>setDraft({...draft,adgCode:e.target.value.replace(/\D/g,'')})}/></label><label><span>Единица измерения *</span><select value={draft.unit} onChange={e=>setDraft({...draft,unit:e.target.value})}><option value="հատ">հատ — шт.</option><option value="կգ">կգ — кг</option><option value="գ">գ — г</option><option value="լ">լ — л</option><option value="մլ">մլ — мл</option></select></label><label><span>Отдел HDM</span><input type="number" min="1" value={draft.department} onChange={e=>setDraft({...draft,department:e.target.value})}/></label><label className="po-check"><input type="checkbox" checked={draft.markingRequired} onChange={e=>setDraft({...draft,markingRequired:e.target.checked})}/><span><b>Требовать Data Matrix / eMark</b><small>Индивидуальный код будет сохраняться в позиции продажи, а не в карточке товара.</small></span></label><label className="po-check"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/><span><b>Товар активен</b><small>Показывать товар на кассе.</small></span></label></div><button className="po-save" onClick={save}><Save/>Сохранить товар</button></div></div>}
 </div>;
}
