import React,{useMemo,useState}from'react';
import{ChevronLeft,Package,Plus,Search,Pencil,Trash2,X,Save,ScanLine,FolderOpen,ArrowUp,ArrowDown}from'lucide-react';
import{getProducts,getCategories,saveProduct,deleteProduct,addCategory,renameCategory,deleteCategory,moveCategory}from'./services/productStore';
const empty=()=>({productCode:'',name:'',category:'',price:'',barcode:'',adgCode:'',unit:'հատ',department:1,markingRequired:false,active:true,emoji:'📦'});
const fmt=v=>new Intl.NumberFormat('ru-RU').format(Number(v)||0)+' ֏';
export default function ProductBackoffice({onBack,onChanged}){
 const[products,setProducts]=useState(()=>getProducts()),[categories,setCategories]=useState(()=>getCategories()),[query,setQuery]=useState(''),[draft,setDraft]=useState(null),[tab,setTab]=useState('products'),[catDraft,setCatDraft]=useState(null),[notice,setNotice]=useState('');
 const filtered=useMemo(()=>products.filter(p=>!query||[p.name,p.productCode,p.barcode,p.adgCode].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase()))),[products,query]);
 const reload=()=>{setProducts(getProducts());setCategories(getCategories());onChanged?.()};
 const message=t=>{setNotice(t);setTimeout(()=>setNotice(''),2600)};
 const edit=p=>setDraft({...p,price:String(p.price)}),create=()=>setDraft({...empty(),category:categories[0]||''});
 const save=()=>{try{saveProduct(draft);setDraft(null);reload();message('Изменения товара сохранены')}catch(e){message(e.message||'Не удалось сохранить товар')}};
 const remove=p=>{if(confirm(`Удалить «${p.name}»?`)){deleteProduct(p.id);reload();message('Товар удалён')}};
 const saveCat=()=>{try{catDraft.original?renameCategory(catDraft.original,catDraft.name):addCategory(catDraft.name);setCatDraft(null);reload();message('Категория сохранена')}catch(e){message(e.message)}};
 const removeCat=c=>{if(!confirm(`Удалить категорию «${c}»?`))return;try{deleteCategory(c);reload();message('Категория удалена')}catch(e){message(e.message)}};
 const move=(c,d)=>{moveCategory(c,d);reload()};
 return <div className="product-office"><div className="po-head"><button className="po-back" onClick={onBack}><ChevronLeft/>Назад</button><div><span>BACK OFFICE</span><h1>Каталог</h1><p>Товары и категории · подготовлено для HDM</p></div><button className="po-add" onClick={tab==='products'?create:()=>setCatDraft({name:'',original:null})}><Plus/>{tab==='products'?'Добавить товар':'Добавить категорию'}</button></div>
 <div className="po-tabs"><button className={tab==='products'?'active':''} onClick={()=>setTab('products')}><Package/>Товары <b>{products.length}</b></button><button className={tab==='categories'?'active':''} onClick={()=>setTab('categories')}><FolderOpen/>Категории <b>{categories.length}</b></button></div>{notice&&<div className="po-notice">{notice}</div>}
 {tab==='products'?<><div className="po-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Название, код товара, штрихкод или ԱՏԳ"/><ScanLine/></div><div className="po-table"><div className="po-row po-columns"><span>Товар</span><span>Цена</span><span>Штрихкод</span><span>ԱՏԳ</span><span>Ед.</span><span/></div>{filtered.map(p=><div className="po-row" key={p.id}><div className="po-product"><i>{p.emoji||'📦'}</i><span><b>{p.name}</b><small>{p.category} · код {p.productCode}{!p.active?' · скрыт':''}{p.markingRequired?' · Data Matrix':''}</small></span></div><b>{fmt(p.price)}</b><span>{p.barcode||'—'}</span><span>{p.adgCode||'—'}</span><span>{p.unit}</span><div className="po-actions"><button onClick={()=>edit(p)}><Pencil/></button><button onClick={()=>remove(p)}><Trash2/></button></div></div>)}</div></>:<div className="po-category-list">{categories.map((c,i)=><div className="po-category-row" key={c}><div><FolderOpen/><span><b>{c}</b><small>{products.filter(p=>p.category===c).length} товаров</small></span></div><div className="po-actions"><button disabled={!i} onClick={()=>move(c,-1)}><ArrowUp/></button><button disabled={i===categories.length-1} onClick={()=>move(c,1)}><ArrowDown/></button><button onClick={()=>setCatDraft({name:c,original:c})}><Pencil/></button><button onClick={()=>removeCat(c)}><Trash2/></button></div></div>)}</div>}
 {draft&&<div className="po-modal-bg"><div className="po-modal"><button className="po-x" onClick={()=>setDraft(null)}><X/></button><div className="po-modal-title"><Package/><div><span>КАРТОЧКА ТОВАРА</span><h2>{draft.id?'Редактировать товар':'Новый товар'}</h2></div></div><div className="po-form"><label><span>Название *</span><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label><span>Цена, ֏ *</span><input inputMode="decimal" value={draft.price} onChange={e=>setDraft({...draft,price:e.target.value})}/></label><label><span>Код товара HDM *</span><input maxLength="50" value={draft.productCode} onChange={e=>setDraft({...draft,productCode:e.target.value})}/></label><label><span>Категория *</span><select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label><span>Штрихкод</span><div className="po-code-input"><input value={draft.barcode} onChange={e=>setDraft({...draft,barcode:e.target.value})}/><button title="Сканер камеры — следующий этап"><ScanLine/></button></div></label><label><span>ԱՏԳ код</span><input value={draft.adgCode} onChange={e=>setDraft({...draft,adgCode:e.target.value.replace(/\D/g,'')})}/></label><label><span>Единица измерения *</span><select value={draft.unit} onChange={e=>setDraft({...draft,unit:e.target.value})}><option value="հատ">հատ — шт.</option><option value="կգ">կգ — кг</option><option value="գ">գ — г</option><option value="լ">լ — л</option><option value="մլ">մլ — мл</option></select></label><label><span>Отдел HDM</span><input type="number" min="1" value={draft.department} onChange={e=>setDraft({...draft,department:e.target.value})}/></label><label className="po-check"><input type="checkbox" checked={draft.markingRequired} onChange={e=>setDraft({...draft,markingRequired:e.target.checked})}/><span><b>Требовать Data Matrix / eMark</b><small>Марка сохраняется в позиции продажи.</small></span></label><label className="po-check"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/><span><b>Товар виден на кассе</b><small>Выключите, чтобы временно скрыть товар без удаления.</small></span></label></div><button className="po-save" onClick={save}><Save/>Сохранить изменения</button></div></div>}
 {catDraft&&<div className="po-modal-bg"><div className="po-modal po-small"><button className="po-x" onClick={()=>setCatDraft(null)}><X/></button><div className="po-modal-title"><FolderOpen/><div><span>КАТЕГОРИЯ</span><h2>{catDraft.original?'Изменить категорию':'Новая категория'}</h2></div></div><label className="po-single-field"><span>Название *</span><input autoFocus value={catDraft.name} onChange={e=>setCatDraft({...catDraft,name:e.target.value})} onKeyDown={e=>e.key==='Enter'&&saveCat()}/></label><button className="po-save" onClick={saveCat}><Save/>Сохранить изменения</button></div></div>}</div>;
}
