import React,{useEffect,useMemo,useRef,useState}from'react';
import{ChevronLeft,Package,Plus,Search,Pencil,Trash2,X,Save,ScanLine,FolderOpen,ArrowUp,ArrowDown,Eye,EyeOff,ImagePlus}from'lucide-react';
import{getProducts,getCategories,saveProduct,deleteProduct,addCategory,renameCategory,deleteCategory,moveCategory}from'./services/productStore';
import{compressProductImage,getProductImage,putProductImage,deleteProductImage}from'./services/productImageStore';
import LanguageSwitcher from'./LanguageSwitcher';
import{useLanguage}from'./services/i18n';
const empty=()=>({productCode:'',name:'',category:'',price:'',barcode:'',adgCode:'',unit:'հատ',department:1,markingRequired:false,active:true,emoji:'📦',hasImage:false});
const fmt=v=>new Intl.NumberFormat('ru-RU').format(Number(v)||0)+' ֏';
function ProductThumb({product}){const[src,setSrc]=useState(null);useEffect(()=>{let url;getProductImage(product.id).then(b=>{if(b){url=URL.createObjectURL(b);setSrc(url)}});return()=>url&&URL.revokeObjectURL(url)},[product.id,product.hasImage]);return src?<img className="po-thumb" src={src}/>:<i>{product.emoji||'📦'}</i>}
export default function ProductBackoffice({onBack,onChanged}){
 const{t}=useLanguage();
 const[products,setProducts]=useState(()=>getProducts()),[categories,setCategories]=useState(()=>getCategories()),[query,setQuery]=useState(''),[draft,setDraft]=useState(null),[tab,setTab]=useState('products'),[catDraft,setCatDraft]=useState(null),[notice,setNotice]=useState(''),[photoBlob,setPhotoBlob]=useState(null),[photoUrl,setPhotoUrl]=useState(null),[removePhoto,setRemovePhoto]=useState(false);const fileRef=useRef();
 const filtered=useMemo(()=>products.filter(p=>!query||[p.name,p.productCode,p.barcode,p.adgCode].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase()))),[products,query]);
 const reload=()=>{setProducts([...getProducts()]);setCategories([...getCategories()]);onChanged?.()};const message=x=>{setNotice(x);setTimeout(()=>setNotice(''),2600)};
 const clearPreview=()=>{if(photoUrl)URL.revokeObjectURL(photoUrl);setPhotoUrl(null);setPhotoBlob(null);setRemovePhoto(false)};
 const openDraft=async p=>{clearPreview();setDraft(p?{...p,price:String(p.price),department:String(p.department||1)}:{...empty(),category:categories[0]||''});if(p?.hasImage){const b=await getProductImage(p.id);if(b)setPhotoUrl(URL.createObjectURL(b))}};
 const choosePhoto=async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{const b=await compressProductImage(f);if(photoUrl)URL.revokeObjectURL(photoUrl);setPhotoBlob(b);setPhotoUrl(URL.createObjectURL(b));setRemovePhoto(false);message(`${t('photo')}: ${Math.max(1,Math.round(b.size/1024))} KB`)}catch(err){message(err.message)}};
 const save=async()=>{if(!draft)return;try{const saved=saveProduct({...draft,price:Number(String(draft.price).replace(',','.')),department:Number(draft.department)||1,hasImage:Boolean(photoBlob||(!removePhoto&&draft.hasImage))});if(photoBlob)await putProductImage(saved.id,photoBlob);else if(removePhoto)await deleteProductImage(saved.id);clearPreview();setDraft(null);reload();message(t('save'));window.dispatchEvent(new CustomEvent('cia-pos-products-changed',{detail:{product:saved}}))}catch(e){message(e.message)}};
 const remove=async p=>{if(confirm(`${t('remove')} «${p.name}»?`)){await deleteProductImage(p.id);deleteProduct(p.id);reload();window.dispatchEvent(new Event('cia-pos-products-changed'))}};
 const saveCat=()=>{try{catDraft.original?renameCategory(catDraft.original,catDraft.name):addCategory(catDraft.name);setCatDraft(null);reload();window.dispatchEvent(new Event('cia-pos-products-changed'))}catch(e){message(e.message)}};const removeCat=c=>{if(!confirm(`${t('remove')} «${c}»?`))return;try{deleteCategory(c);reload()}catch(e){message(e.message)}};const move=(c,d)=>{moveCategory(c,d);reload()};
 return <div className="product-office"><div className="po-head"><button className="po-back" onClick={onBack}><ChevronLeft/>{t('back')}</button><div><span>BACK OFFICE</span><h1>{t('catalog')}</h1><p>{t('prepared')}</p></div><div className="po-head-actions"><LanguageSwitcher compact/><button className="po-add" onClick={tab==='products'?()=>openDraft(null):()=>setCatDraft({name:'',original:null})}><Plus/>{tab==='products'?t('addProduct'):t('addCategory')}</button></div></div><div className="po-tabs"><button className={tab==='products'?'active':''} onClick={()=>setTab('products')}><Package/>{t('products')} <b>{products.length}</b></button><button className={tab==='categories'?'active':''} onClick={()=>setTab('categories')}><FolderOpen/>{t('categories')} <b>{categories.length}</b></button></div>{notice&&<div className="po-notice">{notice}</div>}
 {tab==='products'?<><div className="po-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('search')}/><ScanLine/></div><div className="po-table"><div className="po-row po-columns"><span>{t('product')}</span><span>{t('price')}</span><span>{t('barcode')}</span><span>ԱՏԳ</span><span>{t('unit')}</span><span>{t('action')}</span></div>{filtered.map(p=><div className={'po-row '+(!p.active?'po-hidden-product':'')} key={p.id}><div className="po-product"><ProductThumb product={p}/><span><b>{p.name}</b><small>{p.category} · {p.productCode}</small></span></div><b>{fmt(p.price)}</b><span>{p.barcode||'—'}</span><span>{p.adgCode||'—'}</span><span>{p.unit}</span><div className="po-actions"><button className="po-edit-action" onClick={()=>openDraft(p)}><Pencil/><span>{t('edit')}</span></button><button onClick={()=>remove(p)}><Trash2/></button></div></div>)}</div></>:<div className="po-category-list">{categories.map((c,i)=><div className="po-category-row" key={c}><div><FolderOpen/><span><b>{c}</b><small>{products.filter(p=>p.category===c).length} {t('items')}</small></span></div><div className="po-actions"><button disabled={!i} onClick={()=>move(c,-1)}><ArrowUp/></button><button disabled={i===categories.length-1} onClick={()=>move(c,1)}><ArrowDown/></button><button className="po-edit-action" onClick={()=>setCatDraft({name:c,original:c})}><Pencil/><span>{t('edit')}</span></button><button onClick={()=>removeCat(c)}><Trash2/></button></div></div>)}</div>}
 {draft&&<div className="po-modal-bg"><div className="po-modal"><button className="po-x" onClick={()=>{clearPreview();setDraft(null)}}><X/></button><div className="po-modal-title"><Package/><div><span>{t('product')}</span><h2>{draft.id?`${t('edit')}: ${draft.name}`:t('newProduct')}</h2></div></div><div className="po-photo"><div className="po-photo-preview">{photoUrl?<img src={photoUrl}/>:<ImagePlus/>}</div><div><b>{t('photo')}</b><small>{t('photoHint')}</small><div><button type="button" onClick={()=>fileRef.current?.click()}>{photoUrl?t('replace'):t('addPhoto')}</button>{photoUrl&&<button type="button" onClick={()=>{if(photoUrl)URL.revokeObjectURL(photoUrl);setPhotoUrl(null);setPhotoBlob(null);setRemovePhoto(true)}}>{t('remove')}</button>}</div></div><input ref={fileRef} hidden type="file" accept="image/*" onChange={choosePhoto}/></div><div className="po-form"><label><span>{t('name')} *</span><input value={draft.name} onChange={e=>setDraft(d=>({...d,name:e.target.value}))}/></label><label><span>{t('price')}, ֏ *</span><input value={draft.price} onChange={e=>setDraft(d=>({...d,price:e.target.value}))}/></label><label><span>{t('productCode')} *</span><input maxLength="50" value={draft.productCode} onChange={e=>setDraft(d=>({...d,productCode:e.target.value}))}/></label><label><span>{t('category')} *</span><select value={draft.category} onChange={e=>setDraft(d=>({...d,category:e.target.value}))}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label><span>{t('barcode')}</span><input value={draft.barcode} onChange={e=>setDraft(d=>({...d,barcode:e.target.value}))}/></label><label><span>ԱՏԳ</span><input value={draft.adgCode} onChange={e=>setDraft(d=>({...d,adgCode:e.target.value.replace(/\D/g,'')}))}/></label><label><span>{t('unit')} *</span><select value={draft.unit} onChange={e=>setDraft(d=>({...d,unit:e.target.value}))}><option value="հատ">հատ</option><option value="կգ">կգ</option><option value="գ">գ</option><option value="լ">լ</option><option value="մլ">մլ</option></select></label><label><span>{t('department')}</span><input type="number" min="1" value={draft.department} onChange={e=>setDraft(d=>({...d,department:e.target.value}))}/></label><button type="button" className={'po-visibility '+(draft.active?'on':'off')} onClick={()=>setDraft(d=>({...d,active:!d.active}))}>{draft.active?<Eye/>:<EyeOff/>}<span><b>{draft.active?t('visible'):t('hidden')}</b></span></button><label className="po-check"><input type="checkbox" checked={draft.markingRequired} onChange={e=>setDraft(d=>({...d,markingRequired:e.target.checked}))}/><span><b>{t('marking')}</b></span></label></div><div className="po-modal-actions"><button className="po-cancel" onClick={()=>{clearPreview();setDraft(null)}}>{t('cancel')}</button><button className="po-save" onClick={save}><Save/>{t('save')}</button></div></div></div>}
 {catDraft&&<div className="po-modal-bg"><div className="po-modal po-small"><button className="po-x" onClick={()=>setCatDraft(null)}><X/></button><div className="po-modal-title"><FolderOpen/><div><span>{t('category')}</span><h2>{catDraft.original?t('editCategory'):t('newCategory')}</h2></div></div><label className="po-single-field"><span>{t('categoryName')} *</span><input autoFocus value={catDraft.name} onChange={e=>setCatDraft({...catDraft,name:e.target.value})}/></label><button className="po-save" onClick={saveCat}><Save/>{t('save')}</button></div></div>}</div>;
}
