import React,{useMemo,useState}from'react';
import{ChevronLeft,Warehouse,Truck,Search,Plus,Minus,Package,History,ScanLine,Save,X}from'lucide-react';
import{getProducts}from'./services/productStore';
import{getMovements,getStockMap,getSupplies,createSupply,adjustStock}from'./services/stockStore';
import BarcodeScanner from'./BarcodeScanner';
import'./stock-backoffice.css';
const money=v=>new Intl.NumberFormat('ru-RU').format(Number(v)||0)+' ֏';
export default function StockBackoffice({onBack}){const[tab,setTab]=useState('stock'),[version,setVersion]=useState(0),[query,setQuery]=useState(''),[scanner,setScanner]=useState(false),[supplier,setSupplier]=useState(''),[documentNo,setDocumentNo]=useState(''),[lines,setLines]=useState([]),[notice,setNotice]=useState('');const products=getProducts(),stock=getStockMap(),movements=getMovements(),supplies=getSupplies();const refresh=()=>setVersion(v=>v+1);void version;const filtered=useMemo(()=>products.filter(p=>!query||[p.name,p.barcode,p.productCode].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase()))),[products,query]);const msg=x=>{setNotice(x);setTimeout(()=>setNotice(''),2500)};
 const addProduct=p=>setLines(ls=>{const old=ls.find(x=>x.productId===p.id);return old?ls.map(x=>x.productId===p.id?{...x,qty:x.qty+1}:x):[...ls,{productId:p.id,productName:p.name,barcode:p.barcode||p.productCode,qty:1,purchasePrice:0}]});const scan=code=>{setScanner(false);const p=products.find(x=>String(x.barcode||'')===code||String(x.productCode||'')===code);if(!p)return msg(`Товар ${code} не найден`);if(tab==='supply')addProduct(p);else{setQuery(code);msg(p.name)}};const updateLine=(id,key,value)=>setLines(ls=>ls.map(x=>x.productId===id?{...x,[key]:Number(value)||0}:x));const post=()=>{try{createSupply({supplier,documentNo,items:lines});setLines([]);setSupplier('');setDocumentNo('');refresh();msg('Поставка проведена')}catch(e){msg(e.message)}};const total=lines.reduce((s,x)=>s+x.qty*x.purchasePrice,0);
 return <div className="stock-office"><header className="stock-head"><button onClick={onBack}><ChevronLeft/>Назад</button><div><small>BACK OFFICE</small><h1>Склад и поставки</h1></div></header><nav className="stock-tabs"><button className={tab==='stock'?'active':''} onClick={()=>setTab('stock')}><Warehouse/>Остатки</button><button className={tab==='supply'?'active':''} onClick={()=>setTab('supply')}><Truck/>Новая поставка</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><History/>Движения</button></nav>{notice&&<div className="stock-notice">{notice}</div>}
 {tab==='stock'&&<section className="stock-panel"><div className="stock-toolbar"><div><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Название, EAN или код товара"/></div><button onClick={()=>setScanner(true)}><ScanLine/>Сканировать</button></div><div className="stock-list"><div className="stock-row stock-cols"><span>Товар</span><span>EAN</span><span>Остаток</span><span>Цена</span><span>Коррекция</span></div>{filtered.map(p=><div className="stock-row" key={p.id}><b>{p.name}</b><span>{p.barcode||p.productCode||'—'}</span><strong className={(stock[p.id]||0)<=0?'zero':''}>{stock[p.id]||0} {p.unit||'шт'}</strong><span>{money(p.price)}</span><div className="stock-adjust"><button onClick={()=>{adjustStock(p,(stock[p.id]||0)-1);refresh()}}><Minus/></button><button onClick={()=>{adjustStock(p,(stock[p.id]||0)+1);refresh()}}><Plus/></button></div></div>)}</div></section>}
 {tab==='supply'&&<section className="stock-panel"><div className="supply-meta"><label>Поставщик<input value={supplier} onChange={e=>setSupplier(e.target.value)} placeholder="Название поставщика"/></label><label>Номер документа<input value={documentNo} onChange={e=>setDocumentNo(e.target.value)} placeholder="SUP-001"/></label><button onClick={()=>setScanner(true)}><ScanLine/>Сканировать товар</button></div><div className="supply-lines">{!lines.length?<div className="stock-empty"><Package/><b>Поставка пустая</b><span>Сканируйте товары или добавьте их из каталога ниже</span></div>:lines.map(x=><div className="supply-line" key={x.productId}><b>{x.productName}</b><small>{x.barcode}</small><label>Кол-во<input type="number" min="1" value={x.qty} onChange={e=>updateLine(x.productId,'qty',e.target.value)}/></label><label>Закуп. цена<input type="number" min="0" value={x.purchasePrice} onChange={e=>updateLine(x.productId,'purchasePrice',e.target.value)}/></label><strong>{money(x.qty*x.purchasePrice)}</strong><button className="line-remove" onClick={()=>setLines(ls=>ls.filter(i=>i.productId!==x.productId))}><X/></button></div>)}</div><div className="supply-catalog"><h3>Добавить из каталога</h3>{products.slice(0,12).map(p=><button key={p.id} onClick={()=>addProduct(p)}><Plus/>{p.name}</button>)}</div><footer className="supply-total"><span>Итого: <b>{money(total)}</b></span><button disabled={!lines.length} onClick={post}><Save/>Провести поставку</button></footer></section>}
 {tab==='history'&&<section className="stock-panel"><div className="stock-list"><div className="movement-row movement-cols"><span>Дата</span><span>Товар</span><span>Операция</span><span>Кол-во</span><span>Документ</span></div>{movements.map(m=><div className="movement-row" key={m.id}><span>{new Date(m.createdAt).toLocaleString()}</span><b>{m.productName}</b><span>{m.type}</span><strong className={m.qty<0?'zero':''}>{m.qty>0?'+':''}{m.qty}</strong><span>{m.reference||'—'}</span></div>)}{!movements.length&&<div className="stock-empty"><History/><b>Движений пока нет</b></div>}</div>{supplies.length>0&&<div className="recent-supplies"><h3>Последние поставки</h3>{supplies.slice(0,5).map(s=><div key={s.id}><span>{s.documentNo}</span><span>{s.supplier||'Без поставщика'}</span><b>{money(s.total)}</b></div>)}</div>}</section>}{scanner&&<BarcodeScanner onDetected={scan} onClose={()=>setScanner(false)} title="Сканирование товара" hint={tab==='supply'?'Сканируйте товары поставки один за другим':'Наведите камеру на EAN товара'}/>}</div>}
